spring:
  datasource:
    url: jdbc:mysql://localhost:3306/javaweb
    username: root
    password: 2284
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 20
    minIdle: 10
    maxActive: 100

  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true







